# Generated by Django 5.1.4 on 2025-06-18 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='date_consultation',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='praticien',
            old_name='hopital_id',
            new_name='hopital',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='patient',
        ),
        migrations.AddField(
            model_name='consultation',
            name='disponibilite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.disponibilite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='heure',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='motif',
            field=models.TextField(default='Non spécifié'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('annulée', 'Annulée'), ('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminée', 'Terminée')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.hopital'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='groupe_sanguin',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='poids',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='taille',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tel',
            field=models.CharField(default='0101732970', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='praticien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.praticien'),
        ),
    ]
