# Generated by Django 5.1.4 on 2025-04-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praticien',
            name='hopital_id',
        ),
    ]
