# Generated by Django 5.0.7 on 2025-04-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sexe',
            field=models.CharField(choices=[('m', 'M'), ('f', 'F')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
