# Generated by Django 5.1.4 on 2025-04-23 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_praticien_hopital_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticien',
            name='hopital_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='backend.hopital'),
            preserve_default=False,
        ),
    ]
