# Generated by Django 5.1.4 on 2025-06-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_date_consultation_consultation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.CharField(choices=[('m', 'M'), ('f', 'F')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
