# Generated by Django 5.0.7 on 2025-04-20 17:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_hopital_notification_paiement_praticien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.hopital'),
        ),
        migrations.AddField(
            model_name='disponibilite',
            name='heure_debut',
            field=models.TimeField(default=datetime.time(8, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disponibilite',
            name='heure_fin',
            field=models.TimeField(default=datetime.time(8, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='nom',
            field=models.CharField(default='Alex', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='prenom',
            field=models.CharField(default='Kouadjo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='praticien',
            name='nom',
            field=models.CharField(default='Kouadjo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='praticien',
            name='prenom',
            field=models.CharField(default='Alex', max_length=100),
            preserve_default=False,
        ),
    ]
