# Generated by Django 5.1.4 on 2025-04-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_praticien_hopital_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='praticien',
            old_name='hopital_id',
            new_name='hopital',
        ),
    ]
