# Generated by Django 5.2 on 2025-04-17 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_rapportmedical_consultation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('hopital_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_consultation', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient')),
                ('praticien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.praticien')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('disponibilite_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_disponibilite', models.DateField()),
                ('praticien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.praticien')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date_notification', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('paiement_id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RapportMedical',
            fields=[
                ('id_rapport', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('date_rapport', models.DateField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_ticket', models.DateField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient')),
            ],
        ),
    ]
