# Generated by Django 5.1.4 on 2025-06-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_patient_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticien',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='praticien',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='praticien',
            name='tel',
            field=models.CharField(default='0173287079', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
