# Generated by Django 5.1.4 on 2025-04-23 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_hopital_id_praticien_hopital'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hopital_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.hopital'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialite',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
