# Generated by Django 5.0.7 on 2025-04-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_consultation_hopital_disponibilite_heure_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticien',
            name='langue',
            field=models.CharField(choices=[('en', 'Anglais'), ('fr', 'Français')], default='fr', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='praticien',
            name='specialite',
            field=models.CharField(default='Generaliste', max_length=255),
            preserve_default=False,
        ),
    ]
