# Generated by Django 5.2 on 2025-04-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_hopital_consultation_disponibilite_notification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RapportMedical',
        ),
    ]
