# Generated by Django 5.1.4 on 2025-04-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_customuser_hopital_id_customuser_specialite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='hopital_id',
            new_name='hopital',
        ),
    ]
