# Generated by Django 5.0.7 on 2025-04-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_praticien_langue_praticien_specialite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='hopital',
        ),
    ]
