# Generated by Django 5.1.4 on 2025-04-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_date_consultation_consultation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
    ]
