# Generated by Django 5.2 on 2025-04-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_customuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='praticien',
            old_name='CustomUser',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='changemen123', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
