# Generated by Django 5.1.4 on 2025-05-21 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_ticket_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='motif',
            field=models.TextField(default='Non spécifié'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='praticien',
            field=models.ForeignKey(default='MED-d7c2011b-5a84-4729-83e2-e69334fcc71a', on_delete=django.db.models.deletion.CASCADE, to='backend.praticien'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('annulée', 'Annulée'), ('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminée', 'Terminée')], default='en_attente', max_length=20),
        ),
    ]
