# Generated by Django 5.2 on 2025-04-18 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_delete_rapportmedical'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportMedical',
            fields=[
                ('id_rapport', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('date_rapport', models.DateField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient')),
            ],
        ),
    ]
