# Generated by Django 5.1.4 on 2025-06-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_consultation_motif_consultation_praticien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='ui@gmail.ccom', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='tel',
            field=models.CharField(default='0101012256', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
