# Generated by Django 5.1.4 on 2025-06-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_patient_datenaissance_patient_email_patient_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
