version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "8000:8000" 
    volumes:
      - .:/app
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: backend_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yannalex2004
      POSTGRES_DB: e_santedb
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  db_data: